Batterylevel
jochem725/reactnative-gps-logger pull request #7
Opened 2017-04-28 14:05 UTC by doriandekoning

2017-04-28 14:15 UTC, jochem725 requested changes

2017-04-28 14:15 UTC, jochem725 commented on android/app/src/main/java/com/gpslogger/LocationModule.java
> +        float batlevel = ((float)batteryStatus.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) / (float)scale)* 100.0f;
I think we should add spaces before and after an operand to improve readability `*`

2017-04-28 14:15 UTC, jochem725 commented on js/LocationSampler.ts
> +        this.measurementName = measuremestName
measuremest?

2017-04-28 15:13 UTC, jochem725 submitted a review, later dismissed

2017-04-28 15:13 UTC, bryanvanwijk submitted a review, later dismissed

2017-04-29 10:21 UTC, jochem725 approved these changes

2017-04-29 11:41 UTC, bryanvanwijk approved these changes

2017-04-29 11:44 UTC, merged